#!/usr/bin/env bash
# agent-gateway install - OpenClaw gateway + OS1 voice proxy.
# Idempotent. Run by the ZenCore provisioner. Secrets arrive as env vars:
#   PRIMARY_LLM_API_KEY  (Anthropic key, from required credential)
#   GATEWAY_TOKEN        (generated by provisioner if unset)
set -euo pipefail

OS1_ROOT="/opt/os1"
STATE_DIR="${OS1_ROOT}/.openclaw"
GW_DIR="${OS1_ROOT}/agent-gateway"
COMP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "[agent-gateway] preparing directories"
mkdir -p "${GW_DIR}" "${STATE_DIR}/agents/main/agent" "${STATE_DIR}/workspace" "${STATE_DIR}/wiki/main"

# --- Base packages (Ubuntu) ---
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y curl ca-certificates openssl

# --- Node.js (20+) ---
if ! command -v node >/dev/null 2>&1; then
  echo "[agent-gateway] installing Node.js 20"
  curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  apt-get install -y nodejs
fi

# --- OpenClaw runtime (pin a known-good version in production) ---
if ! command -v openclaw >/dev/null 2>&1; then
  echo "[agent-gateway] installing OpenClaw"
  npm install -g openclaw
fi

# --- Generate a gateway token if the provisioner did not supply one ---
GATEWAY_TOKEN="${GATEWAY_TOKEN:-$(openssl rand -hex 24)}"

# --- Place gateway config from template with secrets substituted ---
echo "[agent-gateway] writing openclaw.json"
sed "s/{{GATEWAY_TOKEN}}/${GATEWAY_TOKEN}/g" \
  "${COMP_DIR}/config.template.json" > "${STATE_DIR}/openclaw.json"

# --- Anthropic auth profile (key from required credential) ---
echo "[agent-gateway] writing auth profile"
cat > "${STATE_DIR}/agents/main/agent/auth-profiles.json" <<JSON
{
  "version": 1,
  "profiles": {
    "anthropic:default": {
      "type": "api_key",
      "provider": "anthropic",
      "key": "${PRIMARY_LLM_API_KEY}"
    }
  }
}
JSON
chmod 600 "${STATE_DIR}/agents/main/agent/auth-profiles.json"

# --- Voice proxy ---
echo "[agent-gateway] installing voice proxy"
cp "${COMP_DIR}/proxy.js" "${GW_DIR}/proxy.js"
[ -f "${GW_DIR}/task-status.json" ] || echo '{ "tasks": [] }' > "${GW_DIR}/task-status.json"

# --- systemd: OpenClaw gateway ---
cat > /etc/systemd/system/agent-gateway.service <<UNIT
[Unit]
Description=OS1 OpenClaw Gateway
After=network-online.target
[Service]
Environment=OPENCLAW_STATE_DIR=${STATE_DIR}
ExecStart=$(command -v openclaw) gateway --port 18789
Restart=always
RestartSec=3
[Install]
WantedBy=multi-user.target
UNIT

# --- systemd: voice proxy ---
cat > /etc/systemd/system/voice-proxy.service <<UNIT
[Unit]
Description=OS1 Voice Proxy
After=agent-gateway.service
[Service]
Environment=OPENCLAW_PORT=18789
Environment=PROXY_PORT=18790
Environment=OPENCLAW_TOKEN=${GATEWAY_TOKEN}
Environment=AUTH_PROFILE_PATH=${STATE_DIR}/agents/main/agent/auth-profiles.json
Environment=STATUS_FILE=${GW_DIR}/task-status.json
Environment=WORK_DIR=${STATE_DIR}/workspace
ExecStart=$(command -v node) ${GW_DIR}/proxy.js
Restart=always
RestartSec=3
[Install]
WantedBy=multi-user.target
UNIT

echo "[agent-gateway] enabling services"
systemctl daemon-reload
systemctl enable --now agent-gateway.service
systemctl enable --now voice-proxy.service

echo "[agent-gateway] done. Health: curl -s http://127.0.0.1:18790/health"
